web_app/urls.py
# -*- coding: utf-8 -*-
"""
urls config
"""
from django.conf import settings
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
# admin.autodiscover()
from django.views.i18n import javascript_catalog

# 公共URL配置
urlpatterns = patterns(
    '',
    # Django后台数据库管理
    url(r'^admin/', include(admin.site.urls)),
    # 添加 account 相关页面
    url(r'^accounts/', include(settings.ACCOUNT_URL)),

    url(r'^doc/', include('home_application.urls')),

    url(r'^wechat/', include('wechat.urls', namespace='wechat', app_name='wechat')),
    url(r'^fta_admin/', include('fta_admin.urls', namespace='fta_admin', app_name='fta_admin')),

    url(r'^', include('fta_solutions_app.urls')),
    url(r'healthz/', "home_application.views.healthz"),
    # 处理JS翻译
    url(r'^jsi18n/(?P<packages>\S+?)/$', javascript_catalog, name='javascript-catalog'),
)

urlpatterns += settings.URL_ENV

web_app/wechat/auth/urls.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community Edition) available.
Copyright (C) 2017-2018 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
""" # noqa

from django.conf.urls import patterns

urlpatterns = patterns('wechat.auth.views', (r'^login/$', 'login'))

web_app/wechat/urls.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community Edition) available.
Copyright (C) 2017-2018 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
""" # noqa
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    'wechat.views',

    url(r'^accounts/', include('wechat.auth.urls')),
    url(r'create_approve', 'create_approve'),
    url(r'^entry/$', 'entry'),
    url(r'^todo/$', 'todo'),
    # 告警详情 by INSTANCE_ID
    url(r'^a/(?P<alarm_instance_id>\d+)/$', 'alarm_detail_fta', name='alarm_detail_fta'),
    url(r'^approve/flow/$', 'approve_flow', name="approve_flow"),
)

web_app/wechat/models.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community Edition) available.
Copyright (C) 2017-2018 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
""" # noqa
import requests
from django.db import models
from django.utils import timezone

from common.log import logger
from enterprise import send_message as send_wechat_message
from fta_solutions_app.models import ApproveCallback, Conf
from project.component import send

rpool = requests.Session()


class Approve(models.Model):
    STATUS = (
        ('WAITING', u"等待"),
        ('TY', u"同意"),
        ('BH', u"驳回")
    )
    obj_id = models.CharField(u"对象ID", max_length=255, blank=True, null=True)
    message = models.TextField(u"审批信息")
    callback_url = models.TextField(u"回调URL", null=True, blank=True)
    status = models.CharField(u"类型", max_length=32, default='WAITING', choices=STATUS)

    approve_users = models.TextField(u"审批人,多个以分号分隔")
    approve_by = models.CharField(u"审批人", max_length=128, blank=True, null=True)
    approve_at = models.DateTimeField(u"审批时间", blank=True, null=True)

    create_at = models.DateTimeField(u"创建时间", auto_now_add=True)
    update_at = models.DateTimeField(u"更新时间", auto_now=True)

    extra = models.TextField(u"其他", blank=True, null=True)

    class Meta:
        verbose_name = u"流程审批"
        verbose_name_plural = u'流程审批'

    def __unicode__(self):
        return '<%s,%s>' % (self.pk, self.message)

    @property
    def to_users(self):
        users = self.approve_users.split(',')
        try:
            super_approver = Conf.get('WECHAT_SUPER_APPROVER')
            super_approver_list = super_approver.split(',') if super_approver else []
            users.extend(super_approver_list)
        except Exception:
            logger.exception(u"WECHAT_SUPER_APPROVER error")
        # 去重, 去空
        users = filter(lambda x: x, set(users))
        return users

    def send_message(self):
        """发送审批单
        """
        content = u"【故障自愈】即将执行 {message},请审核！\n同意请回复: TY {obj_id}\n驳回请回复: BH {obj_id}"
        data = {'message': self.message, 'obj_id': self.pk}
        result = send_wechat_message('|'.join(self.to_users), content.format(**data))
        return result

    def callback(self, action, from_user):
        """回调URL
        """
        try:
            self.status = action
            self.approve_by = from_user
            self.approve_at = timezone.now()
            self.save()

            obj_id = '%s-%s' % (self.id, self.obj_id)
            alarm_id, node_idx = self.obj_id.split('_')
            if self.status == 'TY':
                reason = u"同意（微信审批）"
            else:
                reason = u"驳回（微信审批）"
            approval = 1 if self.status == 'TY' else 0

            app_obj = ApproveCallback(
                obj_id=obj_id,
                alarm_id=int(alarm_id),
                node_idx=int(node_idx),
                approval=approval,
                reason=reason,
                approver=self.approve_by)
            app_obj.save()

            send.wechat(from_user, u"【故障自愈】审批成功")
            # send_wechat_message(from_user, u"【故障自愈】审批成功")
        except Exception as error:
            logger.error('callback: %s' % error)
            send.wechat(from_user, u"【故障自愈】审批失败：%s" % error)
            # send_wechat_message(from_user, u"【故障自愈】审批失败：%s" % error)

web_app/wechat/views.py
# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community Edition) available.
Copyright (C) 2017-2018 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
""" # noqa
import datetime
import json
import re

import xmltodict
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

from common.log import logger
from common.mymako import render_json, render_mako_context
from common.utils import render_ajax
from fta_solutions_app import fta_std
from fta_solutions_app.models import AlarmInstance, Advice, AlarmType, Conf
from fta_utils import fsm_client
from fta_utils.component import bk
from project.conf.decorators import login_exempt
from wechat.auth.utils import get_user_bizs, is_app_in_user_bizs, is_wehcat_super_approver
from wechat.exceptions import APIError
from wechat.models import Approve
from wechat.msg_crypt.WXBizMsgCrypt import WXBizMsgCrypt

STATE_NAME_MAP = dict(fta_std.STATUS_CHOICES)


def _get_login_url():
    """
    微信登录页面
    """
    wechat_app_url = Conf.get('WECHAT_APP_URL')
    return '%saccounts/login/' % wechat_app_url


@login_exempt
@csrf_exempt
def entry(request):
    """微信处理入口
    """
    msg_crypt = WXBizMsgCrypt(
        Conf.get('WECHAT_TOKEN'),
        Conf.get('WECHAT_ENCODING_AES_KEY'),
        Conf.get('WECHAT_CORPID'))
    msg_signature = request.GET.get('msg_signature')
    timestamp = request.GET.get('timestamp')
    nonce = request.GET.get('nonce')

    if request.method == 'GET':
        echostr = request.GET.get('echostr')
        result = msg_crypt.VerifyURL(msg_signature, timestamp, nonce, echostr)
        return HttpResponse(result[1])
    else:
        logger.info('wechat request raw body: %s' % request.body)
        result = msg_crypt.DecryptMsg(request.body, msg_signature, timestamp, nonce)
        logger.info('wechat request decrypt body: %s, %s' % result)
        if result[0] != 0:
            return HttpResponse('403')

        json_obj = xmltodict.parse(result[1])
        msg_type = json_obj['xml']['MsgType']

        # 只处理text请求
        if msg_type != 'text':
            return HttpResponse('403')

        # from_user = json_obj['xml']['FromUserName']
        from_user = user_transfer(json_obj['xml']['FromUserName'])
        content = json_obj['xml']['Content']

        match = re.match(r'(?P<action>\w+) (?P<obj_id>\d+_\d+)$', content)
        if not match:
            return HttpResponse('403')

        action, obj_id = match.groups()
        if action not in ['TY', 'BH']:
            return HttpResponse('403')

        obj = Approve.objects.filter(obj_id=obj_id, status='WAITING').first()
        if not obj:
            return HttpResponse('403')

        if from_user not in obj.to_users:
            return HttpResponse('403')

        try:
            obj.callback(action, from_user)
        except Exception as error:
            logger.error(u"微信审批异常: %s" % error)
            return HttpResponse('500')
        return HttpResponse('200')


@login_exempt
@csrf_exempt
def create_approve(request):
    """创建审批单API
    包含：自愈故障替换API
    """
    try:
        token = request.META.get('HTTP_TOKEN')
        if token != Conf.get('WECHAT_API_TOKEN'):
            raise APIError(u"token不正确")
        try:
            data = json.loads(request.body)
        except Exception:
            raise APIError(u"POST不是合法JSON")

        message = data.get('message')
        if not message:
            raise APIError(u"字段【message】不能为空")

        verifier = data.get('verifier')
        if not verifier:
            raise APIError(u"字段【verifier】不能为空")

        callback_url = data.get('callback_url', '')

        obj_id = data.get('obj_id')
        if not obj_id:
            raise APIError(u"字段【obj_id】不能为空")

        obj = Approve(message=message, obj_id=obj_id, approve_users=verifier, callback_url=callback_url)
        # 保存
        obj.save()
        # 发送微信消息
        obj.send_message()
        content = {'result': True, 'message': u"创建审批单成功", 'data': {'approve_id': obj.id}}
        return render_json(content)

    except APIError as error:
        content = {'result': False, 'message': '%s' % error}
        return render_json(content)
    except Exception as error:
        logger.error(u'create_approval error: %s' % error)
        content = {'result': False, 'message': u"创建审批单异常"}
        return render_json(content)


@csrf_exempt
@login_exempt
@login_required(login_url=_get_login_url())
def todo(request):
    """
    待办事项页面，会把需要审批的告警列出
    """
    username = request.user.username
    now = timezone.now()
    date = now - datetime.timedelta(minutes=45)
    wechat_static_url = Conf.get('WECHAT_STATIC_URL')

    # get approve list of all biz
    approve_list = AlarmInstance.objects.filter(
        status='waiting',
        approved_time=None,
    )
    # 非超级管理员，则只展示用户业务相关的审批信息
    if not is_wehcat_super_approver(username):
        # 获取用户的业务列表
        user_bizs = get_user_bizs(username)
        approve_list = approve_list.filter(cc_biz_id__in=user_bizs)

    alarm_type_maps = {}
    for a in approve_list:
        if a.cc_biz_id not in alarm_type_maps:
            alarm_type_maps[a.cc_biz_id] = AlarmType.get_description_mappings(
                a.cc_biz_id,
            )
        alarm_type_map = alarm_type_maps[a.cc_biz_id]
        a.alarm_type = alarm_type_map[a.alarm_type]
        a.cc_biz_name = a.cc_biz_id

    return render_to_response('wechat/todo.html', RequestContext(request, locals()))


@csrf_exempt
@login_exempt
@login_required(login_url=_get_login_url())
def alarm_detail_fta(request, alarm_instance_id):
    """
    通过自愈告警记录id来查询告警信息
    """
    username = request.user.username
    try:
        inst = AlarmInstance.objects.get(id=alarm_instance_id)
    except AlarmInstance.DoesNotExist:
        return HttpResponseNotFound()
    else:
        # 判断用户是否有操作权限
        if not is_app_in_user_bizs(username, inst.cc_biz_id):
            return render_mako_context(request, 'wechat/wx_error.html', {'message': u"您没有该操作的权限"})

        alarm = json.loads(inst.origin_alarm)
        _append_instance_info(alarm, inst)
        wechat_static_url = Conf.get('WECHAT_STATIC_URL')

        return render_to_response('wechat/alarm_detail.html', RequestContext(request, locals()))


@csrf_exempt
@login_exempt
@login_required(login_url=_get_login_url())
def approve_flow(request):
    """
    执行审批的流程
    """
    username = request.user.username
    id = request.REQUEST.get("id", 0)
    approve = request.REQUEST.get("approve", "false")
    message = request.REQUEST.get("message", 0)
    logger.info("approve_flow: %s" % request.REQUEST)
    try:
        alarm = AlarmInstance.objects.get(id=id)
        # 判断用户是否有操作权限
        if not is_app_in_user_bizs(username, alarm.cc_biz_id):
            logger.error(u"wechat approve_flow username:%s, cc_biz_id:%s" %
                         (username, alarm.cc_biz_id))
            return render_ajax(False, u"您没有该操作的权限")

        # 通过message判断
        if message == 'approved':
            approve = True
            message = u"准许执行自愈套餐-（%s）微信操作" % request.user.username
        else:
            approve = False
            message = u"拒绝执行-（%s）微信操作" % request.user.username
        alarm.approved_user = request.user.username
        alarm.approved_comment = message
        alarm.approved_time = timezone.now()
        alarm.save()
        fsm_client.approve(id, approve, request.user.username, message)
    except Exception, e:
        logger.exception(u"wechat approve_flow")
        return render_ajax(False, unicode(e))
    return render_ajax(True)


def _append_instance_info(alarm, inst):
    """
    append info of alarm_instance onto alarm dict
    """

    alarm['state'] = STATE_NAME_MAP.get(inst.status)
    alarm['failure_type'] = inst.failure_type
    alarm['id'] = inst.id
    alarm['raw'] = inst.raw
    alarm['comment'] = inst.comment
    alarm['alarm_type'] = inst.alarm_type
    alarm['create_time'] = inst.source_time_show
    # alarm['log'] = inst.alarminstancelog_set.filter(level__gte=10)
    alarm['log'] = inst.alarm_log_list.filter(level__gte=10)
    for log in alarm['log']:
        try:
            json_log = json.loads(log.content)
        except Exception:
            json_log = ''
        log.json_content = json_log
    alarm['alarm_instance_id'] = inst.id
    alarm['source_id'] = inst.source_id
    alarm['bpm_task_id'] = inst.bpm_task_id if inst.bpm_task_id else u'无'
    alarm['inc_alarm_id'] = inst.inc_alarm_id if inst.inc_alarm_id else u'无'
    alarm['cc_biz_id'] = inst.cc_biz_id
    alarm['origin_alarm'] = inst.origin_alarm
    alarm['cc_topo_set'] = inst.cc_topo_set
    alarm['cc_app_module'] = inst.cc_app_module
    # alarm['uwork_id'] = inst.uwork_id
    subject = None
    if inst.ip:
        alarm['ip'] = inst.ip
        subject = alarm['ip']
    if inst.alarm_type in fta_std.ALARM_TYPE_ONLINE:
        subject = alarm['cc_topo_set']
    if subject:
        advice_dict = {}
        advices = Advice.objects.filter(
            subject=subject, status='fresh',
            create_time__gt=timezone.now() - datetime.timedelta(days=7))
        for advice in advices:
            if not advice_dict.get(advice.advice_def.id):

web_app/templates/wechat/alarm_detail.html
{% extends "wechat/base.html" %}
{% load url from future %}

{% block title %}{{ alarm.service }}{% endblock %}

{% block main %}
{% if alarm.state %}
    <h3 style="width:60%;float:left">自愈状态【{{ alarm.state }}】</h3>
    <div style="clear:both"></div>
    {% if alarm.comment %}<p>{{ alarm.comment }}</p>{% endif %}
{% else %}
    <h3>告警详情</h3>
{% endif %}

<div class="ui-bar ui-bar-a">
    <h3>内容</h3>
</div>
<div class="ui-body ui-body-a">
    <p>{{ alarm.raw }}</p>
</div>

<div class="ui-bar ui-bar-a">
    <h3>类型</h3>
</div>
<div class="ui-body ui-body-a">
    <p>{{ alarm.alarm_type }}</p>
</div>

<div class="ui-bar ui-bar-a">
    <h3>产生时间</h3>
</div>
<div class="ui-body ui-body-a">
    <p>{{ alarm.create_time|date:"Y-m-d H:i:s" }}</p>
</div>

{% if alarm.attr_id %}
<div class="ui-bar ui-bar-a">
    <h3>特性ID</h3>
</div>
<div class="ui-body ui-body-a">
    <p>{{ alarm.attr_id }}</p>
</div>
{% endif %}

<div class="ui-bar ui-bar-a">
    <h3>集群</h3>
</div>
<div class="ui-body ui-body-a">
    <p>{{ alarm.cc_topo_set }}</p>
</div>

<div class="ui-bar ui-bar-a">
    <h3>模块</h3>
</div>
<div class="ui-body ui-body-a">
    <p>{{ alarm.cc_app_module }}</p>
</div>


<div class="ui-bar ui-bar-a">
    <h3>参考信息</h3>
</div>
<div class="ui-body ui-body-a">
    <p>自愈记录ID: {{ alarm.alarm_instance_id }}</p>
</div>

{% if alarm.advice %}
<div class="ui-bar ui-bar-a">
    <h3>相关告警</h3>
</div>
<div class="ui-body ui-body-a">
    {% for advice in alarm.advice %}
        <p style="white-space: normal;">{{ advice.alarm_detail_description|safe }}</p>
    {% endfor %}
</div>
{% endif %}

{% if alarm.log %}
<div class="ui-bar ui-bar-a">
    <h3>处理日志</h3>
</div>
<div class="ui-body ui-body-a">
    {% for l in alarm.log %}
    {% if alarm.log.level >= 20 %}
    <p style="white-space: normal;">{{ l.content }}</p>
    {% endif %}
    {% endfor %}
</div>
{% endif %}
{% endblock %}

web_app/templates/wechat/base.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
<meta content="telephone=no" name="format-detection"/>

<link rel="stylesheet" href="{{wechat_static_url}}js/jquery-mobile/1.4.2/jquery.mobile.min.css" />
<script src="{{wechat_static_url}}js/jquery/1.11.0/jquery.min.js"></script>
<script src="{{wechat_static_url}}js/jquery-mobile/1.4.2/jquery.mobile.min.js"></script>
<script src="{{wechat_static_url}}js/underscore.js/1.6.0/underscore-min.js"></script>

</head>
<body>

<div id="wrapper" data-role="page">

    {% block header %}{% endblock %}

    <div role="main" class="ui-content">
        {% block main %}{% endblock %}
    </div><!-- /content -->

    {% block footer %}{% endblock %}

</div><!-- /page -->

{% block extra %}{% endblock %}

<script type="text/javascript">
$(document).on("pagecreate", function(event, ui) {
    {% block script %}{% endblock %}
});
</script>

</body>
</html>

web_app/templates/wechat/todo.html
{% extends "wechat/base.html" %}
{% load url from future %}

{% block title %}等待您的审批{% endblock %}

{% block main %}
{% if not approve_list %}
<h3>无待办事项</h3>
{% endif %}
<ul data-role="listview">
    {% for alarm in approve_list %}
	<li data-role="list-divider">{{ alarm.source_time_show }}<span class="ui-li-count">
        {{ alarm.cc_biz_name }}
    </span></li>
    <li>
        <h3>{{ alarm.alarm_type }}</h3>
        <p>{{ alarm.ip }}</p>
        <p>
        <a href="{% url 'wechat:alarm_detail_fta' alarm.id %}">
            {{ alarm.raw }}
        </a>
        </p>
        <p>
            {{ alarm.comment }}
        </p>
        <div event_name="{{alarm.id}}">
            <a href="###" comment='approved' class="approve-btn ui-btn ui-btn-inline ui-icon-check ui-btn-icon-left">准许执行自愈套餐</a>
            <a href="###" comment='rejected' class="approve-btn ui-btn ui-btn-inline ui-icon-delete ui-btn-icon-left">拒绝执行</a>
        </div>

    </li>
    {% endfor %}
</ul>

<br />

{% endblock %}

{% block script %}
$(document).on('click', '.approve-btn', function(e) {
    e.preventDefault();
    e.stopImmediatePropagation();
    var submit_data = {
        'id': $(this).parent('div').attr('event_name'),
        'message': $(this).attr('comment'),
        'approve': 'true',
        'client': 'wechat'
    }
    $.ajax({
        url: "{% url 'wechat:approve_flow' %}",
        type: "POST",
        data: submit_data,
        beforeSend: function() {
            $.mobile.loading("show");
        },
        complete: function() {
            $.mobile.loading("hide");
        },
        success: function(data) {
            $('div[event_name='+ submit_data.event_name +']').hide();
            window.location.reload();
        }
    });
});
{% endblock %}

web_app/templates/wechat/wx_error.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>蓝鲸智云</title>
	<meta charset="utf8">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">
	<style type="text/css">
		body{font-family:微软雅黑,Helvetica,"Helvetica Neue","segoe UI Light","Kozuka Gothic Pro";font-size:15px;background-color:#EFEFF4;-webkit-user-select:none;color:#666;}
		html,body,ul,li,p{padding:0px;margin:0px;}
		ul{list-style: none;}
		.wrp{padding: 35px 15px 15px; text-align: center;}
		.icon_msg.warn{width: 100px;height: 100px;vertical-align: middle;display: inline-block;background:url("${STATIC_URL}images/weixin/icon_error.svg") no-repeat center;}
		.text_area{display: inline-block;text-align:center;line-height:1.5em}
		.text_area h2{font-size:16px;color:#000;margin-bottom:18px;font-weight:normal;}
		.text_area .text_content{display:inline-block;padding:0px 15px}
		.text_area .text_content p{text-align:left;}
		.icon_area {margin-bottom: 25px;}
		.group:after{content: "."; display: block; height: 0; font-size: 0; clear: both; visibility: hidden;}
		ul li .li_title{width:7em;text-align:right;float:left;}
		ul li .li_content{margin-left:7em;word-break:break-all;word-wrap:break-word;}
		.footer{padding:30px 0px 20px;width:100%;color:#808080;font-size:11px;}
		.footer a{color:#007aff;text-decoration:none;}
	</style>
	</head>
	<body>
		<div class="wrp">
			<div class="icon_area"><i class="icon_msg warn"></i></div>
			<div class="text_area">
			    % if message:
			    <h2>${message}</h2>
			    % else:
                <h2>请求非法！</h2>				
                % endif
			</div>
			<div class="footer">
				<p>如有疑问，请QQ咨询(800802001)</p>
			</div>
	    </div>
    </body>
</html>